### ISSUE TITLE
pg_settings is global?

### ISSUE THREAD

**Issue by jjb** [gocardless/activerecord-safer_migrations#54]
Thanks for a really neat project!

question: doesn't `UPDATE  pg_settings` change the global state of the database, therefor affecting behavior of all other connections/sessions from all other clients?

**Comment by Sinjo** [comment]
Hey, glad you like it! You may also find our more recent project, [Nandi](https://github.com/gocardless/nandi) interesting.

The last paragraph of [these docs](https://www.postgresql.org/docs/12/view-pg-settings.html) is hopefully useful. Specifically:

> The change only affects the value used by the current session.

**Comment by jjb** [comment]
Thanks for the quick reply! I needed to RTFM 🤦

**Comment by Sinjo** [comment]
No worries. The Postgres docs are a double-edged sword: they're very comprehensive, but sometimes that makes finding what you need a needle-in-a-haystack exercise!
