### ISSUE TITLE
Rubygems release

### ISSUE THREAD

**Issue by plribeiro3000** [gocardless/activerecord-safer_migrations#59]
I noticed there is code at master for version [`3.0.0`](https://github.com/gocardless/activerecord-safer_migrations/commit/d5dc26bea40c596d07e3ad918f21e68583ffc9d5) but no tag at rubygems. Could we release the new version to rubygems please?

**Comment by nickcampbell18** [comment]
How rude of us! I've just pushed it now, thanks for raising a ticket!

**Comment by plribeiro3000** [comment]
Awesome. Thank you for the fast answer and fix!
