### ISSUE TITLE
Can't reopen issue

### ISSUE THREAD

**Issue by plribeiro3000** [gocardless/activerecord-safer_migrations#75]
@nickcampbell18 i still have issues regarding #60 

As you suggested i've tried to reopen the issue but i can't. I think it might be related to the repo configurations.

**Comment by nickcampbell18** [comment]
Really sorry @plribeiro3000 I no longer work at GoCardless and thus don't maintain this gem. @Sinjo would you mind funneling this to the right place please?

**Comment by Sinjo** [comment]
Hey @plribeiro3000 I've reopened it for you. Does your comment from the 5th November have all the latest context on the problem you're having?

**Comment by plribeiro3000** [comment]
Yeas. It does. Thanks for reopening!
